#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define CONFIG_USE_PSRAM_OCTAL_MODE 1 // 1: octal mode, 0: quad mode

// 屏方向使能位, 顺时针旋转
#define CONFIG_DISPLAY_ROTATION_0 0 // 默认屏排线在南边,竖屏
#define CONFIG_DISPLAY_ROTATION_90 0 // 排线在东边,横屏
#define CONFIG_DISPLAY_ROTATION_180 0 // 排线在北边,竖屏
#define CONFIG_DISPLAY_ROTATION_270 1 // 排线在西边,横屏

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#define AUDIO_CODEC_PA_PIN GPIO_NUM_9
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_2
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_1
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

// BUTTON
#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#define POWER_BUTTON_GPIO GPIO_NUM_48


#if CONFIG_DISPLAY_ROTATION_90 || CONFIG_DISPLAY_ROTATION_270
#define DISPLAY_WIDTH 296
#define DISPLAY_HEIGHT 240
#else
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 296
#endif

#if CONFIG_DISPLAY_ROTATION_90
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#elif CONFIG_DISPLAY_ROTATION_180
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#elif CONFIG_DISPLAY_ROTATION_270
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY true
#else
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#endif

#if CONFIG_DISPLAY_ROTATION_90 || CONFIG_DISPLAY_ROTATION_270
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#else
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#endif

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_TE_PIN GPIO_NUM_14
#define DISPLAY_SPI_CS_PIN GPIO_NUM_21
#define DISPLAY_SPI_DC_PIN GPIO_NUM_16
#define DISPLAY_SPI_RST_PIN GPIO_NUM_15
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_17
#define DISPLAY_SPI_MISO_PIN GPIO_NUM_NC
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_18

// BATTERY
#define BATTERY_LEVEL_DETECT_PIN GPIO_NUM_10
#define BATTERY_CHARGING_DETECT_PIN GPIO_NUM_39
#define BATTERY_CHARGED_DETECT_PIN GPIO_NUM_40

// TF CARD
#define TF_CARD_SD_DETECT_PIN GPIO_NUM_47
#define TF_CARD_SD_CLK_PIN GPIO_NUM_36
#define TF_CARD_SD_CMD_PIN GPIO_NUM_35
#define TF_CARD_SD_DATA0_PIN GPIO_NUM_37
#define TF_CARD_SD_DATA1_PIN GPIO_NUM_38
#define TF_CARD_SD_DATA2_PIN GPIO_NUM_33
#define TF_CARD_SD_DATA3_PIN GPIO_NUM_34

// headphone detect
#define HEADPHONE_DETECT_PIN GPIO_NUM_3

#endif // _BOARD_CONFIG_H_
